# Site settings
title:       Tania Shatilova
email:       tatashat@gmail.com
author:      Tania Shatilova
description: "Thougts on tech, development, life hacks"
baseurl:     ""
url:         "http://sufflavus.github.io"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: Tania

# Social icons
show_social_icons: true
github_username: sufflavus
bitbucket_username: 
stackoverflow_id: 
twitter_username: 
google_plus_id: 
linkedin_username: tatiana-shatilova-26009481
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
  
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
  
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

# http://jekyllrb.com/docs/permalinks/
# http://joshualande.com/short-urls-jekyll/
permalink: "/:title"

gems:
  - jekyll-gist